home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^level/', views.level, name="level"),
    url(r'^home/static/media/pdf/(?P<filename>\{w{40})/$', views.pdf_download, name="pdf_download"),
    url(r'^first_level/', views.first_level, name="first_level"),
    url(r'^second_level/', views.second_level, name="second_level"),
    url(r'^third_level/', views.third_level, name="third_level"),
    url(r'^practical_test/', views.image_form_upload, name="image_form_upload"),
    url(r'^quiz/(?P<level_id>[0-9]+)/$', views.quiz_question, name='quiz_question'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^save/', views.save, name='save'),
]

homeania/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_view
from home.views import UserFormView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/', include('home.urls', namespace="home")),

    #Registartion/login and logout URL
    url(r'^register/', UserFormView.as_view(), name='register'),
    url(r'^login/', auth_view.login, name="login"),


    #password Reset URL
    url(r'^passowrd_reset/$', auth_view.password_reset, name='password_reset'),
    url(r'^passowrd_reset/done/$', auth_view.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_view.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$',auth_view.password_reset_complete, name='password_reset_complete'),

]

home/models.py
from django.db import models
from django.contrib.auth.models import User

class Practical_test(models.Model):
    description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='C:\Users\guptaane\PycharmProjects\Homeania-Photocert\Homeania-Photocert\home\static\media',max_length=2000)

    def __str__(self):
        return self.description


class First_level(models.Model):
    question = models.CharField(max_length=200)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    correct_option = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.question


class Second_level(models.Model):
    question = models.CharField(max_length=200)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    correct_option = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.question

class Third_level(models.Model):
    question = models.CharField(max_length=200)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    correct_option = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.question

home/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Practical_test,Second_level,First_level,Third_level
from django.views.generic import View
from .form import UserForm,ImageForm
import os


def index(request):
    return render(request,'home/base.html')

@login_required(login_url='/login/')
def level(request):
    return render(request,'home/level_page.html')

@login_required(login_url='/login/')
def pdf_download(request, filename):
  path = os.expanduser('~/media/pdf/')
  wrapper = FileWrapper(file(filename,'rb'))
  response = HttpResponse(wrapper, content_type=mimetypes.guess_type(filename)[0])
  response['Content-Disposition'] = "attachment; filename=" + filename
  return response

def first_level(request):
    return render(request,'home/first_level.html')

def second_level(request):
    return render(request,'home/second_level.html')

def third_level(request):
    return render(request,'home/third_level.html')

def logout_view(request):
    logout(request)
    return render(request,'registration/logout.html')


class UserFormView(View):
    form_class = UserForm
    template_name = 'Registration/registration_form.html'

    #Display Blank Form
    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name,{'form':form})

    #process form Data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #cleaned (normalized) data

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #return user objects if credentials are correct
            user = authenticate(username=username,password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('home:level')

        return render(request,self.template_name,{'form':form})

@login_required(login_url='/login/')
def image_form_upload(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home:index')
    else:
        form = ImageForm()
    return render(request,'home/Image_upload_form.html', {'form':form})

@login_required(login_url='/login/')
def quiz_question(request,level_id):
    id= level_id.__str__()
    if id == '1':
        context = First_level.objects.all()
        return render(request, 'home/quiz.html', {'context': context})
    if id == '2':
        context = Second_level.objects.all()
        return render(request, 'home/quiz.html', {'context': context})
    if id == '3':
        context = Third_level.objects.all()
        return render(request, 'home/quiz.html', {'context': context})

def save(request):
    for x in range(1,10):
        print ">>>>>"
        print 'q'+x.__str__()
        p=request.POST.get("q", None)
        if p in ['a','b','c','d']:
            print "Matchhhhh"
        print p
    return redirect('home:index')

templates/home/Image_upload_form.html
<!DOCTYPE html>
<html>
<body>
{% extends "home/base.html" %}
{% block content %}
    <div class="ImageUpload">
    <div class="panel-body">
        <h3 align="center">Upload an Image</h3>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data" >
            {% csrf_token %}
            {% include 'home/form_template.html' %}
            <div class="form-group">
                <div class="form-group" align="center">
                    <input type="submit" class="button" value="Upload" >
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/home/base.html
<head lang="en" xmlns="http://www.w3.org/1999/html">

    <title>Photo Cert</title>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}

<link href="{% static "home.css" %}" rel="stylesheet" type="text/css" />

</head>
<body>

<style type="text/css"> a.nounderline {text-decoration: none; }</style>

<div class="container">

<header>
    <div id="logoName">
        <span class="firstHalf">home</span><span class="secondHalf">ania</span>
    </div>
    <div id="subLogo">
        <span class = "byLine">real estate marketing services</span>
    </div>
</header>

<div id="titleLine">
    <span class="title">PHOTOGRAPHER CERTIFICATION PROGRAM</span>
</div>

{% block content %}
    <div id="secondline">
        <span class="second">Give Wings to your Passion </span></br>
        <a href="{% url 'login' %}" class="button" >Login</a>
        </br>
        <h5>---------First time here?---------</h5>
        </br>
        <a href="{% url 'register' %}" class="button">Create an account</a>
    </div>

    <div id="footer">
         Copyright © 2017 Homeania Corporation. All rights reserved.
    </div>

{% endblock %}
</div>



</body>






templates/home/first_level.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
        {% load static %}


<link href="{% static "style.css" %}" rel="stylesheet" type="text/css" />
</head>
<body>

<header>
    <div id="logoName">
        <span class="firstHalf">home</span><span class="secondHalf">ania</span>
    </div>
    <div id="subLogo">
        <span class = "byLine">real estate marketing services</span>
    </div>
</header>

<div id="titleLine1">
    <span class="title1">PHOTOGRAPHER CERTIFICATION PROGRAM</span></br>
    <span class="title1">LEVEL 1</span>
</div>

<div id="nav" align="right" >
    <span class="firstHalf" aria-hidden="true">Hello {{request.user.username | title}}</span>&nbsp;|
    <a href="/static/media/pdf/Real state Photography Guide.pdf" class="nonunderline" target="_blank" ">&nbsp; Download</a> |
    <a href="#"><span aria-hidden="true"></span>&nbsp; Logout</a>
</div>

<div id="Introduction">
    <span class="Intro">Photography has never been more important to selling real estate than it is today.</br>
        The markets are heating up again and demand for real estate creates demand for photography.</br>
        This is good news to photographers, but like any business,</br> there is plenty of competition.
        If you are new to real estate and architecture photography.</br></span>
        <p><b><a href="{% url 'home:quiz_question' 1 %}" class="nonunderline" ><h3>Quiz</h3></a></b></p>
        <p><b><a href="{% url 'home:image_form_upload' %}" class="nonunderline" ><h2>Practical Test</h2></a></b></p>
</body>
</html>

templates/home/form_template.html
{% for field in form %}
    <div class="form-group"align="center" >
        <div class=form-error>
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="form-label" >{{ field.label_tag }}</label>
        <div class="form-field">{{ field }}</div>
        </br>
    </div>
{% endfor %}

templates/home/level_page.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>


    {% load static %}

<link href="{% static "style.css" %}" rel="stylesheet" type="text/css" />
</head>
<body>

<style type="text/css"> a.nounderline {text-decoration: none; }</style>


<div class="container">

<header>
    <div id="logoName">
        <span class="firstHalf">home</span><span class="secondHalf">ania</span>
    </div>
    <div id="subLogo">
        <span class = "byLine">real estate marketing services</span>
    </div>
</header>

<div id="titleLine">
    <span class="title">PHOTOGRAPHER CERTIFICATION PROGRAM</span>
</div>

<div id="nav" align="right" >
    <b><span class="firstHalf" aria-hidden="true">Hello {{request.user.username | title}}</span>&nbsp;</b> |
    <a href="{% url 'home:logout' %}"><span aria-hidden="true"></span>&nbsp; Logout</a>
</div>

<div id="secondline">
    <span class="second">Choose the level you would like to work on</span>
</div>

<div id="firstpart">

    <div id="first1">
        <a href="{% url 'home:first_level' %}" class="nounderline"><span class="level" >LEVEL 1</span></a></br></br>
        <span class="leveltext">Introduction to our</br>system and real estate</br>photography</br>Completion of this</br>course will allow you</br>to shoot our standard</br>orders</span>
    </div>

    <div id="first2">
        <a href="{% url 'home:second_level' %}" class="nounderline"><span class="level" >LEVEL 2</span></a></br></br>
        <span class="leveltext">Real Estate</br>Videography and HDR</br>photography</br>Completion of this</br>level will allow you to</br>shoot our deluxe</br>package</span>
    </div>

</div>

<div id="secondpart">
    <a href="{% url 'home:third_level' %}" class="nounderline"><span class="level" >LEVEL 3</span></a></br></br>
    <span class="leveltext">Aerial Photography</br>and beyond.</br>Completion of this</br>level will allow you to</br>shoot our aerial</br>add-on package.</span>
</div>

</body>
</html>

templates/home/quiz.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% load static %}
<link href="{% static "style.css" %}" rel="stylesheet" type="text/css" />


<div id="titleLine1">
    <span class="title1">PHOTOGRAPHER CERTIFICATION PROGRAM</span></br>
    <span class="title1">LEVEL 1</span>
</div>

<div id="nav" align="right" >
    <span class="firstHalf" aria-hidden="true">Hello {{request.user.username | title}}</span>&nbsp;|
    <a href="#"><span aria-hidden="true"></span>&nbsp; Logout</a>
</div>

{% for val in context %}
    <h2>{{ val.question }}</h2>

<form action="" method="post">
    {% csrf_token %}
    <label for="q1a"><input type="radio" name="q{{ forloop.c }}" value="a" id="q1a">{{ val.option1 }}</label><br/>
    <label for="q1b"><input type="radio" name="q" value="b" id="q1b">{{ val.option2 }}</label><br/>
    <label for="q1c"><input type="radio" name="q" value="c" id="q1c">{{ val.option3 }}</label><br/>
    <label for="q1d"><input type="radio" name="q" value="d" id="q1d">{{ val.option4 }}</label><br/>
    </br>
{% endfor %}

</br>
</form>
<a href="{% url 'home:save' %}" class="button">Submit</a>

</body>
</html>

templates/home/second_level.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
        {% load static %}


<link href="{% static "style.css" %}" rel="stylesheet" type="text/css" />
</head>
<body>

<header>
    <div id="logoName">
        <span class="firstHalf">home</span><span class="secondHalf">ania</span>
    </div>
    <div id="subLogo">
        <span class = "byLine">real estate marketing services</span>
    </div>
</header>

<div id="titleLine1">
    <span class="title1">PHOTOGRAPHER CERTIFICATION PROGRAM</span></br>
    <span class="title1">LEVEL 2</span>
</div>

<div id="nav" align="right" >
    <b><span class="firstHalf" aria-hidden="true">Hello {{request.user.username | title}}</span>&nbsp;</b> |
    <b><a href="/static/media/pdf/Real Estate and Videography and HDR.pdf" class="nonunderline" target="_blank" ">&nbsp; Download</a></b> |
    <b><a href="#"><span aria-hidden="true"></span>&nbsp; Logout</a></b>
</div>

<div id="Introduction">
    <span class="Intro">The most common method used to create 'good enough' real estate photos is HDR:</br>
                        whether it is tonemapping or exposure fusion,</br>
                        HDR is definitely the most-used method for real estate and beginner interior photographers.</br>
                        There are plenty of comments debating the use of HDR and the use of flash in the comments.</br>
                        Flash users insult HDR users, HDR users insult flash users, everyone cuts a knee open, and everyone goes home disappointed.</br>
                        It is as dependable as the sun rising and setting</span>
    <span class="options">
         <b><a href="{% url 'home:quiz_question' 2 %}" class="nonunderline"><h2>Quiz</h2></a></b>
         <b><a href="{% url 'home:image_form_upload' %}" class="nonunderline"><h2>Practical Test</h2></a></b>
    </span>

</body>
</html>

templates/home/third_level.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
        {% load static %}


<link href="{% static "style.css" %}" rel="stylesheet" type="text/css" />
</head>
<body>

<header>
    <div id="logoName">
        <span class="firstHalf">home</span><span class="secondHalf">ania</span>
    </div>
    <div id="subLogo">
        <span class = "byLine">real estate marketing services</span>
    </div>
</header>

<div id="titleLine1">
    <span class="title1">PHOTOGRAPHER CERTIFICATION PROGRAM</span></br>
    <span class="title1">LEVEL 3</span>
</div>

<div id="nav" align="right" >
    <b><span class="firstHalf" aria-hidden="true">Hello {{request.user.username | title}}</span>&nbsp;</b> |
    <a href="/static/media/pdf/Aerial Photography Guide.pdf" class="nonunderline" target="_blank" ">&nbsp; Download</a>|
    <a href="#"><span aria-hidden="true"></span>&nbsp; Logout</a>
</div>

<div id="Introduction">
    <span class="Intro">High up on our photography bucket list is to try an aerial photo shoot for the first time.</br>
                        The aerial perspective is mesmerizing to say the least.</br>
                        Whether it’s a traditional aerial landscape like this one,</br>
                        or stunning abstract aerials like the ones scattered throughout this post,</br>
                        every aerial photograph we’ve seen makes us want to take to the skies just a little bit more until—someday</br>
                        soon—we’ll bite the financial bullet and just do it.</span>
    <p><b><a href="{% url 'home:quiz_question' 3 %}" class="nonunderline"><h2>Quiz</h2></a></b></p>
    <p><b><a href="{% url 'home:image_form_upload' %}" class="nonunderline"><h2>Practical Test</h2></a></b></p>

</body>
</html>